"""Thin FastAPI layer over sukb. Streams puller events via SSE."""

from __future__ import annotations

import asyncio
import json
import os
import re
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from queue import Empty, Queue
from typing import Any

import yaml
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from sse_starlette.sse import EventSourceResponse

from ..config import SyncConfig
from ..ingest.dead_letter import clear_failure, list_failures, load_failure
from ..ingest.puller import ConfluencePuller, PullEvent, load_credentials
from ..chat import query as query_mod
from ..chat import sessions as sessions_mod


PROJECT_ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = Path(os.environ.get("KB_CONFIG", PROJECT_ROOT / "sync_config.yaml"))
ENV_PATH = PROJECT_ROOT / ".env"  # project-local .env
FRONTEND_DIR = PROJECT_ROOT / "frontend"


def _load_env_file(env_path: Path) -> None:
    """Populate os.environ from .env at module import so secrets (Atlassian
    + Anthropic) are available to every endpoint, not just the auth path."""
    if not env_path.exists():
        return
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path)
    except ImportError:
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


_load_env_file(ENV_PATH)


@dataclass
class Job:
    job_id: str
    space_key: str
    status: str = "pending"  # pending | running | done | failed
    events: list[dict[str, Any]] = field(default_factory=list)
    queue: Queue = field(default_factory=Queue)
    summary: dict[str, Any] | None = None
    started_at: str = ""
    finished_at: str = ""
    error: str | None = None


# In-memory job registry. Single-process v1 — Redis/RQ comes later if needed.
JOBS: dict[str, Job] = {}
JOBS_LOCK = threading.Lock()


def get_config() -> SyncConfig:
    return SyncConfig.load(CONFIG_PATH)


def get_puller() -> ConfluencePuller:
    email, token = load_credentials(ENV_PATH)
    if not email or not token:
        raise HTTPException(
            status_code=503,
            detail="ATLASSIAN_EMAIL or ATLASSIAN_TOKEN missing from environment / .env",
        )
    return ConfluencePuller(get_config(), email, token)


app = FastAPI(title="su-kb-pipeline — Confluence ingestion UI backend")


# --- auth + spaces -----------------------------------------------------------


@app.get("/api/auth/status")
def auth_status() -> dict[str, Any]:
    email, token = load_credentials(ENV_PATH)
    return {
        "email": email or None,
        "token_loaded": bool(token),
        "last_call_ts": None,
        "env_path": str(ENV_PATH),
        "env_path_exists": ENV_PATH.exists(),
    }


@app.get("/api/spaces")
def list_spaces() -> JSONResponse:
    """Return cached inventory + per-space enabled/disabled state from config."""
    config = get_config()
    if not config.inventory_path.exists():
        return JSONResponse({"spaces": [], "error": f"inventory missing at {config.inventory_path}"})
    # Inventory was generated by PowerShell on Windows, which emits a UTF-8 BOM.
    inv = json.loads(config.inventory_path.read_text(encoding="utf-8-sig"))
    spaces = []
    for s in inv:
        key = s.get("key")
        spaces.append({
            "key": key,
            "id": s.get("id"),
            "name": s.get("name"),
            "type": s.get("type"),
            "pages_current": s.get("pages_current", 0),
            "category": config.category_for(key),
            "enabled": config.is_enabled(key),
            "included": config.is_included(key, s.get("pages_current", 0)),
        })
    spaces.sort(key=lambda s: (not s["enabled"], -s["pages_current"]))
    return JSONResponse({
        "spaces": spaces,
        "total": len(spaces),
        "enabled_keys": config.enabled_keys,
        "min_pages_threshold": config.min_pages_threshold,
    })


# --- jobs --------------------------------------------------------------------


@app.post("/api/spaces/{key}/pull")
def start_pull(key: str) -> dict[str, str]:
    config = get_config()
    if not config.is_enabled(key):
        raise HTTPException(403, detail=f"Space {key} is not enabled in sync_config.yaml (v1 = ITSAI only)")

    # Per-space lock: two simultaneous pulls of the same space would race on
    # the markdown files and .sync-state.json. Reject the second call instead.
    with JOBS_LOCK:
        active = [j for j in JOBS.values() if j.space_key == key and j.status in ("pending", "running")]
        if active:
            raise HTTPException(
                409,
                detail=f"Space {key} already has an active pull (job_id={active[0].job_id}). "
                       f"Wait for it to finish or cancel before starting another.",
            )
        job_id = uuid.uuid4().hex[:12]
        job = Job(job_id=job_id, space_key=key, started_at=_now())
        JOBS[job_id] = job

    threading.Thread(target=_run_pull, args=(job,), daemon=True).start()
    return {"job_id": job_id, "space_key": key}


def _run_pull(job: Job) -> None:
    job.status = "running"
    try:
        puller = get_puller_for_job()
        for evt in puller.pull_space(job.space_key):
            record = {"kind": evt.kind, "space_key": evt.space_key, "ts": _now(), **evt.payload}
            job.events.append(record)
            job.queue.put(record)
            if evt.kind == "completed":
                job.summary = evt.payload.get("summary")
        job.status = "done"
    except Exception as e:
        job.status = "failed"
        job.error = str(e)
        job.queue.put({"kind": "job_error", "error": str(e), "ts": _now()})
    finally:
        job.finished_at = _now()
        job.queue.put({"kind": "stream_end", "ts": _now()})


def get_puller_for_job() -> ConfluencePuller:
    email, token = load_credentials(ENV_PATH)
    if not email or not token:
        raise RuntimeError("ATLASSIAN_EMAIL/ATLASSIAN_TOKEN missing")
    return ConfluencePuller(get_config(), email, token)


@app.get("/api/jobs/{job_id}/events")
async def job_events(job_id: str):
    job = JOBS.get(job_id)
    if not job:
        raise HTTPException(404, "job not found")

    async def gen():
        # Replay events that fired before client connected
        for past in list(job.events):
            yield {"event": past["kind"], "data": json.dumps(past)}
        # Stream new ones
        while True:
            try:
                ev = job.queue.get(timeout=0.5)
            except Empty:
                if job.status in ("done", "failed"):
                    break
                await asyncio.sleep(0.1)
                continue
            yield {"event": ev["kind"], "data": json.dumps(ev)}
            if ev["kind"] in ("stream_end", "job_error"):
                break

    return EventSourceResponse(gen())


@app.get("/api/jobs/{job_id}/result")
def job_result(job_id: str) -> dict[str, Any]:
    job = JOBS.get(job_id)
    if not job:
        raise HTTPException(404, "job not found")
    return {
        "job_id": job.job_id,
        "space_key": job.space_key,
        "status": job.status,
        "started_at": job.started_at,
        "finished_at": job.finished_at,
        "summary": job.summary,
        "error": job.error,
        "events": job.events,
    }


@app.get("/api/jobs")
def list_jobs() -> dict[str, Any]:
    return {
        "jobs": [
            {
                "job_id": j.job_id,
                "space_key": j.space_key,
                "status": j.status,
                "started_at": j.started_at,
                "finished_at": j.finished_at,
                "summary": j.summary,
            }
            for j in sorted(JOBS.values(), key=lambda j: j.started_at, reverse=True)
        ]
    }


# --- output browser ----------------------------------------------------------


@app.get("/api/pages")
def list_pages_endpoint(space: str | None = None) -> dict[str, Any]:
    config = get_config()
    root = config.raw_path
    pages = []
    if not root.exists():
        return {"pages": [], "total": 0}
    for md in root.rglob("*.md"):
        fm = _read_frontmatter(md)
        if space and fm.get("space_key") != space:
            continue
        pages.append({
            "page_id": fm.get("page_id"),
            "title": fm.get("title"),
            "space_key": fm.get("space_key"),
            "ancestor_path": fm.get("ancestor_path"),
            "last_modified": fm.get("last_modified"),
            "version": fm.get("version"),
            "maintenance_signal": fm.get("maintenance_signal"),
            "last_sync_status": fm.get("last_sync_status"),
            "warnings_count": len(fm.get("conversion_warnings") or []),
            "path": str(md.relative_to(root)),
        })
    pages.sort(key=lambda p: (p.get("space_key") or "", p.get("title") or ""))
    return {"pages": pages, "total": len(pages)}


@app.get("/api/pages/{page_id}")
def get_page_endpoint(page_id: str) -> dict[str, Any]:
    config = get_config()
    md_path = _find_page(config.raw_path, page_id)
    if not md_path:
        raise HTTPException(404, f"page {page_id} not found in {config.raw_path}")
    text = md_path.read_text(encoding="utf-8")
    fm, body = _split_frontmatter(text)

    # Look for the dead-letter entry if we still have the raw XML
    dl_root = config.output_dir / "conversion-failures"
    raw_xml_hint = None
    if dl_root.exists():
        for f in dl_root.rglob(f"{page_id}.json"):
            try:
                raw_xml_hint = load_failure(f).get("storage_xml")
                break
            except Exception:
                pass

    return {
        "page_id": page_id,
        "frontmatter": fm,
        "markdown": body,
        "path": str(md_path),
        "storage_xml": raw_xml_hint,  # null unless this page was previously dead-lettered
    }


# --- failures ----------------------------------------------------------------


@app.get("/api/failures")
def get_failures() -> dict[str, Any]:
    config = get_config()
    return {"failures": list_failures(config.output_dir / "conversion-failures")}


@app.get("/api/failures/{page_id}")
def get_failure_detail(page_id: str) -> dict[str, Any]:
    config = get_config()
    dl_root = config.output_dir / "conversion-failures"
    matches = list(dl_root.rglob(f"{page_id}.json"))
    if not matches:
        raise HTTPException(404, "no failure record for that page_id")
    return load_failure(matches[0])


@app.post("/api/failures/{page_id}/retry")
def retry_failure(page_id: str) -> dict[str, Any]:
    config = get_config()
    dl_root = config.output_dir / "conversion-failures"
    matches = list(dl_root.rglob(f"{page_id}.json"))
    if not matches:
        raise HTTPException(404, "no failure record for that page_id")
    failure = load_failure(matches[0])
    space_key = failure.get("space_key")
    if not space_key:
        raise HTTPException(400, "failure record has no space_key")

    # For v1 retry = re-run the whole space. Single-page retry is v1.5 (needs a
    # narrower puller entrypoint).
    with JOBS_LOCK:
        active = [j for j in JOBS.values() if j.space_key == space_key and j.status in ("pending", "running")]
        if active:
            raise HTTPException(
                409,
                detail=f"Space {space_key} already has an active pull (job_id={active[0].job_id}).",
            )
        job_id = uuid.uuid4().hex[:12]
        job = Job(job_id=job_id, space_key=space_key, started_at=_now())
        JOBS[job_id] = job
    # Clear the failure record so the retry's outcome is the new authoritative one.
    clear_failure(matches[0])
    threading.Thread(target=_run_pull, args=(job,), daemon=True).start()
    return {"job_id": job_id, "space_key": space_key, "note": "v1 retry triggers a full-space re-pull"}


# --- config view -------------------------------------------------------------


@app.get("/api/config")
def get_config_endpoint() -> dict[str, Any]:
    config = get_config()
    return {
        "path": str(config.config_path),
        "raw_yaml": Path(config.config_path).read_text(encoding="utf-8"),
        "parsed": {
            "space_categories": config.space_categories,
            "default_space_category": config.default_space_category,
            "min_pages_threshold": config.min_pages_threshold,
            "include_keys": config.include_keys,
            "excluded_keys": config.excluded_keys,
            "enabled_keys": config.enabled_keys,
            "output_dir": str(config.output_dir),
            "api_base": config.api_base,
            "rate_limit_per_sec": config.rate_limit_per_sec,
        },
    }


# --- query -------------------------------------------------------------------


@app.post("/api/query")
def post_query(body: dict[str, Any]) -> JSONResponse:
    """Answer a single question against the corpus. v1.5 chat-interface entrypoint.

    Body: {question: str, mode: "raw" | "raw+wiki" (default "raw+wiki"),
           max_pages: int? (default no cap)}
    """
    question = (body.get("question") or "").strip()
    if not question:
        raise HTTPException(400, "question is required")
    mode = body.get("mode") or "raw+wiki"
    if mode not in ("raw", "raw+wiki"):
        raise HTTPException(400, f"mode must be 'raw' or 'raw+wiki', got {mode!r}")
    max_pages = body.get("max_pages")

    try:
        result = query_mod.answer_query(
            question=question,
            config=get_config(),
            mode=mode,
            max_pages=int(max_pages) if max_pages else None,
        )
    except RuntimeError as e:
        # ANTHROPIC_API_KEY missing or SDK not installed — surface clearly.
        raise HTTPException(503, str(e))
    return JSONResponse(result.to_dict())


@app.get("/api/query/status")
def query_status() -> dict[str, Any]:
    """Cheap pre-flight: is the corpus loadable, is the API key configured?"""
    config = get_config()
    raw = query_mod.load_raw_corpus(config)
    wiki = query_mod.load_wiki_corpus(config)
    return {
        "raw_pages": len(raw),
        "wiki_pages": len(wiki),
        "wiki_dir": str(config.output_dir / "wiki"),
        "wiki_dir_exists": (config.output_dir / "wiki").exists(),
        "api_key_loaded": bool(os.environ.get("ANTHROPIC_API_KEY")),
        "model": query_mod.MODEL,
    }


# --- query sessions ----------------------------------------------------------


@app.get("/api/query/sessions")
def list_query_sessions() -> dict[str, Any]:
    return {"sessions": sessions_mod.list_sessions(get_config())}


@app.get("/api/query/sessions/{sid}")
def get_query_session(sid: str) -> dict[str, Any]:
    try:
        return sessions_mod.load_session(get_config(), sid)
    except FileNotFoundError as e:
        raise HTTPException(404, str(e))
    except ValueError as e:
        raise HTTPException(400, str(e))


@app.post("/api/query/sessions")
def save_query_session(body: dict[str, Any]) -> dict[str, Any]:
    turns = body.get("turns") or []
    name = body.get("name") or None
    if not isinstance(turns, list) or not turns:
        raise HTTPException(400, "turns must be a non-empty list")
    return sessions_mod.save_session(get_config(), turns, name=name)


@app.patch("/api/query/sessions/{sid}")
def rename_query_session(sid: str, body: dict[str, Any]) -> dict[str, Any]:
    name = body.get("name") or ""
    try:
        return sessions_mod.rename_session(get_config(), sid, name)
    except FileNotFoundError as e:
        raise HTTPException(404, str(e))
    except ValueError as e:
        raise HTTPException(400, str(e))


@app.delete("/api/query/sessions/{sid}")
def delete_query_session(sid: str) -> dict[str, Any]:
    try:
        ok = sessions_mod.delete_session(get_config(), sid)
    except ValueError as e:
        raise HTTPException(400, str(e))
    if not ok:
        raise HTTPException(404, "session not found")
    return {"ok": True, "session_id": sid}


# --- frontend static --------------------------------------------------------


if FRONTEND_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(FRONTEND_DIR)), name="static")

    @app.get("/")
    def index() -> FileResponse:
        return FileResponse(str(FRONTEND_DIR / "index.html"))


# --- helpers ----------------------------------------------------------------


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _read_frontmatter(md_path: Path) -> dict[str, Any]:
    try:
        text = md_path.read_text(encoding="utf-8")
    except OSError:
        return {}
    fm, _ = _split_frontmatter(text)
    return fm


def _split_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---"):
        return {}, text
    m = re.match(r"^---\n(.*?)\n---\n?", text, re.DOTALL)
    if not m:
        return {}, text
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    return fm, text[m.end():]


def _find_page(root: Path, page_id: str) -> Path | None:
    if not root.exists():
        return None
    for md in root.rglob(f"{page_id} -*.md"):
        return md
    return None
